### ISSUE TITLE
Python's icon

### ISSUE THREAD

**Issue by Denkiri21** [Jorricks/macos-notifications#10]
Hi Jorricks!

I want to ask you if you've looked into changing the default Python icon that pops up in the notification on the left and, if you have, could you share how to do it.

Thanks for the code!

**Comment by Jorricks** [comment]
Hey @Denkiri21,

First of all, thanks for opening the issue and second, sorry for responding this late. I looked into this quite a bit but the only thing you can do is completely change the Python interpreter image in Macos settings. This means you would change one permanent image for the other. Which probably b isn't what you are looking for. You can however add a small side image, which I usually use for my projects.

**Comment by Jorricks** [comment]
I have made this limitation clear in the README here;
https://github.com/Jorricks/macos-notifications/commit/e91cba44a6b153eae5160bf9d90785af8e3544dd
