### ISSUE TITLE
mac_notifications-utilizing process never exits

### ISSUE THREAD

**Issue by dstromberg** [Jorricks/macos-notifications#17]
Here's a test program that demonstrates the problem:

```
#!/usr/bin/env python3

import sys
import time

from mac_notifications import client


def noop(*args, **kwargs):
    """No operation: do nothing."""
    pass


class Callback:
    def __init__(self):
        self.called_back = False

    def callback(self, *args, **kwargs):
        print(f'args: {args}')
        print(f'kwargs: {kwargs}')
        self.called_back = True


if __name__ == '__main__':
    cb = Callback()
    client.create_notification(
        title="title",
        subtitle="subtitle",
        icon=None,
        action_button_str="Acknowledge",
        action_callback=cb.callback,
    )
    while not cb.called_back:
        print('waiting...')
        sys.stdout.flush()
        time.sleep(1)
    print('hello!')
```

It never exits.  It does the print('hello!') fine, but the process just keeps running.

What do I need to do to get the process to exit normally?

Thanks!

**Comment by Jorricks** [comment]
Hello @dstromberg,

Thanks for opening an issue for your question.
In this particular case this is expected. The reason for this is that we don't know whether we can still expect more actions or not. Therefore, you need to call `client.stop_listening_for_callbacks()` once you want to quit. This will kill the background thread that is listening for responses and thus will make your application quit.

An example of this is shown here;
https://github.com/Jorricks/macos-notifications/blob/6f0741dae497a13d70734d233fa97d94f48c6c3f/examples/notification_with_action.py#L24
