### ISSUE TITLE
Doesn't support threading

### ISSUE THREAD

**Issue by azhuchkov** [Jorricks/macos-notifications#19]
Got the following error trying to create notification:

```
  File "/lib/python3.12/site-packages/mac_notifications/manager.py", line 48, in __init__
    signal.signal(signal.SIGINT, handler=self.catch_keyboard_interrupt)
  File "/lib/python3.12/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: signal only works in main thread of the main interpreter
```

**Comment by Spuxy** [comment]
Curious question. Why would u want to use this as multithreading app ? I mean if u want to use in more threads, just make it in rust,go whatever and let their own schedulers to spawn their threads, where those threads can run some py script (like this example) or you can compile it into binary thru python c compiler and exec this like any other bin command.

**Comment by Jorricks** [comment]
First of all, thank you for raising this @azhuchkov. I think you can use threading, but you will need to launch the notification from the main thread. That means you'll have to setup communication channels between your new threads and the main threads.
I will add this to the README to be more clear.

@Spuxy I do understand your point, but switching between programming languages might be easy for you, but might make it much more complicated for someone else's use-case if they don't know these languages.

Closing the tread :)
