### ISSUE TITLE
Icon is blocked?

### ISSUE THREAD

**Issue by mietzen** [Jorricks/macos-notifications#2]
When running your examples the icon is somehow "blocked"?

![image](https://user-images.githubusercontent.com/31704359/190969188-568dd352-2b5f-442d-88d5-0e80d66d5deb.png)

Is this known? 

```
macOS 12.6
MacBook Pro (14-inch, 2021) M1Pro
Python 3.10.6
macos-notifications    0.1.5
pyobjc-core            8.5
pyobjc-framework-Cocoa 8.5
```

**Comment by Jorricks** [comment]
I have struggled quite a bit with this as well.
Is it possible you did not give it the required permissions as mentioned here; https://discussions.apple.com/thread/253503524?

**Comment by Jorricks** [comment]
Closing this issue as there has been no reply for a long time.
