### ISSUE TITLE
Link in documentation with instructions on enabling notifications points to a wrong location

### ISSUE THREAD

**Issue by mrdc** [Jorricks/macos-notifications#21]
Hello,

Link in documentation with instructions on enabling notifications points to a wrong location.

Issue is here:
`https://jorricks.github.io/macos-notifications/faq/`
`you first need to allow Python to create notifications. Instructions on this can be found [here]`

And it points to a wrong location:
`https://www.jetbrains.com/idea/guide/tips/enable-soft-wrap/#:~:text=You%20can%20enable%20soft%20wrap,more%20file%20types%20by%20default.).`

Thanks

**Comment by Jorricks** [comment]
Thanks for raising this @mrdc!
Updated the documentation here; https://github.com/Jorricks/macos-notifications/commit/6a5cc88634795ec18e32b74083e7097628b50205.

Let me know if something is still unclear
