### ISSUE TITLE
macos-notifications 0.1.5 does not give a notification on python 3.10

### ISSUE THREAD

**Issue by dstromberg** [Jorricks/macos-notifications#5]
I'm using homebrew CPython 3.10, macos-notifications 0.1.5 and MacOS 12.6 on an Intel Mac.

This script is what I'm using to test macos-notifications:
```
#!/usr/bin/env python3

from time import sleep

from mac_notifications import client

if __name__ == '__main__':
    client.create_notification(
        title="title",
        subtitle="subtitle",
        icon=None,
    )
    sleep(60)
```
I'm running it with:
```/usr/local/bin/python3.10 tst```

But no notification comes up.

Any suggestions?

Thanks!

**Comment by Jorricks** [comment]
Hey @dstromberg,

Have you checked the documentation and checked your settings in MacOS?
Here we have a screenshot of what your settings should look like. Maybe you did not whitelist python to show notifications; https://jorricks.github.io/macos-notifications/faq/
