### ISSUE TITLE
Installation conflicts with latest version of PyObjC

### ISSUE THREAD

**Issue by workflowsguy** [Jorricks/macos-notifications#6]
`macos-notifications` has a dependency `pyobjc-core==8.5`.
On my machine with the current pyobjc-core (9.0.1), this causes `python3 -m pip install macos-notifications` to fail.

Would it be possible to upgrade the dependency?

Thanks!

**Comment by Jorricks** [comment]
Should be fixed with the newest 0.1.6. Thanks for reporting!
