### ISSUE TITLE
RuntimeError involving freeze_support()

### ISSUE THREAD

**Issue by oxxie** [Jorricks/macos-notifications#9]
Hi,

Using Python 3.9.4 I try to create a notification with the following line:

`client.create_notification("Title TEST", "Subtitle TEST", "Text TEST")`

Instead of the notification popping up, the following error is raised:

```
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

Somebody knows what's going on? Would appreciate the help, thanks! 🙏🏻

**Comment by Jorricks** [comment]
Hi Oxxie,

Thank you for opening the issue.
Could you please provide a minimal example to reproduce (instead of just the line)?

**Comment by oxxie** [comment]
Of course @Jorricks, here it is:

```
from mac_notifications import client

client.create_notification("Title TEST", "Subtitle TEST", "Text TEST")
```

Running the code above already raises the described RuntimeError exception. There's nothing more to it, I'm afraid. Hope this helps!

**Comment by Jorricks** [comment]
> Of course @Jorricks, here it is:
> 
> ```
> from mac_notifications import client
> 
> client.create_notification("Title TEST", "Subtitle TEST", "Text TEST")
> ```
> 
> Running the code above already raises the described RuntimeError exception. There's nothing more to it, I'm afraid. Hope this helps!

Thanks for the quick reply.

It's because we require you to have 

```
if __name__ == "__main__":
    your_function() 
```

This is a limitation enforced from the dependency we have on the MasOS system.

**Comment by oxxie** [comment]
Ah, I see! I have tested it with the requirement as described and it works 👍🏻 Thanks so much, will close this issue!
